name: Java build

on:
  push:
    branches: [ master ]
   
permissions:
  contents: read

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache gradle
        uses: actions/cache@v3
        with: 
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle


      - name: Build with Gradle
        run: ./gradlew :core:standalone:build

      - name: ls core
        run: cd ./core/standalone/bin && ls -all
      - name: ls
        run: cd ./bin && ls -all

      - name: SCP jar file
        uses: appleboy/scp-action@master
        with:
          username: ec2-user
          host: ${{ secrets.EC2_HOST }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: ./core/standalone/bin/*.jar
          target: ~/openwhisk/core/standalone/bin
          strip_components: 2
          